server:
  port: 8081
management:
  security:
    enabled: false
spring:
  application:
    name: auth-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${mysql.host:localhost}:3306/cloudauth?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  redis:
    host: ${redis.host:localhost}
    port: 6379

  thymeleaf:
    prefix: classpath:/templates/ #注意页面和action指向路径开头不要加/
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
    servlet:
      multipart:
        max-file-size: 2MB
    resources:
      static-locations: classpath:static/,file:static/
