server:
  port: 8004

spring:
  application:
    name: auth-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${mysql.host:localhost}:3306/cloudauth?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  redis:
    host: ${redis.host:localhost}
    port: 6379
